### ISSUE TITLE
How about using Conventional Commits on Velociraptor?

### ISSUE THREAD

**Issue by joelwallis** [umbopepato/velociraptor#20]
This issue is more of a suggestion than a feature addition. I think Velociraptor would benefit from using something like [Conventional Commits](https://www.conventionalcommits.org) a lot. Being able to tell what a commit do would be great, and keeping yourself up to date with what's going on with the codebase by reading the commit log would be easier.

What do you think? Does it make sense for you as a project maintainer?

**Comment by umbopepato** [comment]
Definitely! I was planning to adopt a stricter commit style eventually, especially to facilitate generating changelogs and GH release notes. A `commitlint` + `@commitlint/config-conventional` commit-msg hook wouldn't hurt as well.
