### ISSUE TITLE
add possibility for `velociraptor.yaml` file

### ISSUE THREAD

**Issue by eankeen** [umbopepato/velociraptor#21]
was wondering if there were any considerations to allow the naming of the file to be `velociraptor.yaml`, `velociraptor.json`, etc. instead of just `scripts.yaml`? would be willing to create pr for this - thoughts?

**Comment by umbopepato** [comment]
I thought of that name at some point but eventually went with `scripts` for brevity. Didn't think of using both as alternatives though, not a bad idea! 🙂
