### ISSUE TITLE
Script flag arguments are consumed by vr

### ISSUE THREAD

**Issue by han-tyumi** [umbopepato/velociraptor#26]
Currently when trying to pass flag arguments to my script they are instead consumed by vr.

> ![image](https://user-images.githubusercontent.com/13040345/82734693-a0aa0a00-9cea-11ea-8d06-1719e966af0a.png)
> Expected

> ![image](https://user-images.githubusercontent.com/13040345/82734648-51fc7000-9cea-11ea-88a0-c6c5dd2d624a.png)
> Actual

**Comment by umbopepato** [comment]
@han-tyumi thanks for reporting this.

Looks like the CLI framework consumes unknown options (positional arguments should work though).
Until this is fixed I can suggest you to use version `1.0.0-beta.3` in order to forward options correctly to scripts:

```
deno install --allow-read --allow-env --allow-run -f -n vr https://deno.land/x/velociraptor@v1.0.0-beta.3/cli.ts
```

**Comment by umbopepato** [comment]
@han-tyumi this should be solved in `v1.0.0-beta.8`. I'll leave you to close this if it works

**Comment by han-tyumi** [comment]
@umbopepato Just tested your changes; works correctly now. Thanks!

**Comment by Nisgrak** [comment]
Didn't work in 1.0.0-beta.9

**Comment by umbopepato** [comment]
@Nisgrak are you getting the `Unknown option` error?
Can you show the complete `vr` command you're launching?

**Comment by Nisgrak** [comment]
@umbopepato I tested again and it's work, sorry.
