### ISSUE TITLE
Broken link in Visual Studio Marketplace

### ISSUE THREAD

**Issue by David-Else** [umbopepato/velociraptor#31]
https://marketplace.visualstudio.com/items?itemName=umbo.vscode-velociraptor

Repository https://github.com/umbopepato/vscode-velociraptor << broken

**Comment by umbopepato** [comment]
@David-Else thanks for reporting this. Actually the link is right but the repository was initially private. I've now made it public though

**Comment by David-Else** [comment]
GrOoVy :)
