### ISSUE TITLE
Deno 1.1.2 breaks velocipraptor

### ISSUE THREAD

**Issue by newtack** [umbopepato/velociraptor#35]
vr --help
sh: 0: getcwd() failed: No such file or directory
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', cli/worker.rs:141:16

**Comment by umbopepato** [comment]
Hi @newtack, thanks for reporting this.

What os are you on? Also, are you using `.ts` config files?

**Comment by newtack** [comment]
Ubuntu 18.0.4, not using tsconfig.

**Comment by umbopepato** [comment]
I mean velociraptor's `.ts` [config files](https://github.com/umbopepato/velociraptor#script-files)

**Comment by newtack** [comment]
Got it. I haven't made any changes to them.

**Comment by umbopepato** [comment]
This is probably related to https://github.com/denoland/deno/issues/6057.
Try to run `deno info scripts.ts` and delete the `compiled` file.

**Comment by newtack** [comment]
That fixed it. Thanks!
