### ISSUE TITLE
broken modules using Deno 1.2.0

### ISSUE THREAD

**Issue by yoshixmk** [umbopepato/velociraptor#36]
with deno 1.2.0 update some packages will be broken due to changes in lib std.

I get an error with all other commands that are broken they will throw errors.   
I tried to reinstall and cache reloading but couldn't.   
I get the following error
```Shell
$ vr start
error: TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname
                 ~~~
    at https://deno.land/std@v0.56.0/path/win32.ts:917:18

TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname;
                 ~~~
    at https://deno.land/std@v0.56.0/path/posix.ts:438:18

Found 2 errors.
```

**Comment by newtack** [comment]
Getting the same error

**Comment by tranzystorek-io** [comment]
https://github.com/denosaurs/denon/issues/74 <- same issue in denon, std version needs to be bumped to 0.61.0

**Comment by umbopepato** [comment]
Thanks for reporting this!

`beta.13` should fix this, can you confirm it works?

**Comment by yoshixmk** [comment]
Thank you very much.   
With the fix, I confirmed to resolved issue.  
Close :)

**Comment by MuhammadTahirkhan** [comment]
beta.13 

explain
